In [1]:
#Imports here
import numpy as np

In [2]:
# Task 0 - Create Confusion
"""
Function that creates a confusion matrix
"""
def create_confusion_matrix(labels, logits):
    """
    labels: one-hot numpy.ndarray of shape (m, classes) containing the correct labels
        m: number of data points
        classes: number of classes
    logits: one-hot numpy.ndarray of shape (m, classes) containing the predicted labels
    Returns a confusion numpy.ndarray of shape (classes, classes)
        row indices: correct labels
        column indixes: predicted labels
    """
    confusion_matrix = np.zeros([labels.shape[1], logits.shape[1]])
    # print(confusion_matrix)
    true_label_index = np.where(labels == 1)[1]
    true_logits_index = np.where(logits == 1)[1]
    # print(true_label_index)
    # print(true_logits_index)
    indexes = list(zip(true_label_index, true_logits_index))
    unique, counts = np.unique(indexes, return_counts=True, axis=0)
    # print(unique)
    # print(counts)
    confusion_matrix[unique[:,0], unique[:,1]] = counts
    # print(confusion_matrix)
    
    return(confusion_matrix)

In [3]:
# 0-main
lib = np.load('labels_logits.npz')
labels = lib['labels']
logits = lib['logits']

np.set_printoptions(suppress=True)
confusion = create_confusion_matrix(labels, logits)
print(confusion)
np.savez_compressed('confusion.npz', confusion=confusion)

[[4701.    0.   36.   17.   12.   81.   38.   11.   35.    1.]
 [   0. 5494.   36.   21.    3.   38.    7.   13.   59.    7.]
 [  64.   93. 4188.  103.  108.   17.  162.   80.  132.   21.]
 [  30.   48.  171. 4310.    2.  252.   22.   86.  128.   52.]
 [  17.   27.   35.    0. 4338.   11.   84.    9.   27.  311.]
 [  89.   57.   45.  235.   70. 3631.  123.   33.  163.   60.]
 [  47.   32.   87.    1.   64.   83. 4607.    0.   29.    1.]
 [  26.   95.   75.    7.   58.   18.    1. 4682.   13.  200.]
 [  31.  153.   82.  174.   27.  179.   64.    7. 4003.  122.]
 [  48.   37.   39.   71.  220.   49.    8.  244.   46. 4226.]]


In [4]:
# Task 1 - Sensitivity
"""
Function that calculates the sensitivity for each class in a confusion matrix
"""
def sensitivity(confusion):
    """
    confusion: numpy.ndarray of shape (classes, classes)
        row: indices that represent the correct labels
        column: indices that represent the predicted labels
    Returns a numpy.ndarray of shape (classes, ) containing the sensitivity of
        each class
    """
    true_positives = np.diag(confusion)
    row_sum = np.sum(confusion, axis=1)
    false_negative = row_sum - true_positives
    sensitivity = true_positives / (true_positives + false_negative)
    return sensitivity

In [5]:
# 1-main
confusion = np.load('confusion.npz')['confusion']

np.set_printoptions(suppress=True)
print(sensitivity(confusion))

[0.95316302 0.96759422 0.84299517 0.84493237 0.89277629 0.80581447
 0.93051909 0.9047343  0.82672449 0.84723336]


In [6]:
# Task 2 - Precision
"""
Function that calculates the precision for each class in a confusion matrix
"""
def precision(confusion):
    """
    confusion: numpy.ndarray of shape (classes, classes)
        row: indices that represent the correct labels
        column: indices that represent the predicted labels
    Returns a numpy.ndarray of shape (classes, ) containing the precision of
        each class
    """
    true_positives = np.diag(confusion)
    col_sum = np.sum(confusion, axis=0)
    false_positives = col_sum - true_positives
    precision = true_positives / (true_positives + false_positives)
    return precision

In [7]:
# 2-main
confusion = np.load('confusion.npz')['confusion']

np.set_printoptions(suppress=True)
print(precision(confusion))

[0.93033841 0.91020543 0.87359199 0.87264628 0.88494492 0.83298922
 0.90050821 0.90648596 0.86364617 0.84503099]


In [8]:
# Task 3. Specificity
"""
Function that calculates the specificity for each class in a confusion matrix
"""
def specificity(confusion):
    """
    confusion: numpy.ndarray of shape (classes, classes)
        row: indices that represent the correct labels
        column: indices that represent the predicted labels
    Returns a numpy.ndarray of shape (classes, ) containing the specificity of
        each class
    """
    true_positives = np.diag(confusion)
    col_sum = np.sum(confusion, axis=0)
    false_positives = col_sum - true_positives
    row_sum = np.sum(confusion, axis=1)
    false_negatives = row_sum - true_positives
    true_negatives = np.sum(confusion) - true_positives - false_positives - false_negatives
    speficity = true_negatives / (true_negatives + false_positives)
    return speficity

In [9]:
# 3-main
np.random.seed(5)
c = np.random.randint(10, 20)
confusion = np.random.randint(0, 100, (c, c))
print(specificity(confusion))

[0.91553398 0.94039083 0.91365132 0.92460589 0.91623693 0.92398695
 0.95227556 0.93264469 0.91346974 0.91496309 0.92830757 0.92361305
 0.92094371]


In [10]:
# Task 4 - F1 score
"""
Calculate the F1 score of a confusion matrix
"""
def f1_score(confusion):
    """
    confusion: numpy.ndarray of shape (classes, classes)
        row: indices that represent the correct labels
        column: indices that represent the predicted labels
    Returns a numpy.ndarray of shape (classes, ) containing the F1 score of
        each class
    """
    # prec = precision(confusion)
    # sens = sensitivity(confusion)
    # F1 = prec + sens
    # return F1 / 2
    
    
    true_positives = np.diag(confusion)
    col_sum = np.sum(confusion, axis=0)
    false_positives = col_sum - true_positives
    row_sum = np.sum(confusion, axis=1)
    false_negatives = row_sum - true_positives
    F1 = (2 * true_positives) / ((2 * true_positives) + false_positives + false_negatives)
    return F1

In [11]:
# 4-main
confusion = np.load('confusion.npz')['confusion']

np.set_printoptions(suppress=True)
print(f1_score(confusion))

[0.94161242 0.93802288 0.8580209  0.85856574 0.88884336 0.81917654
 0.91526771 0.90560928 0.8447821  0.84613074]
